version: "3"
services:
  # Web
  nginx:
    build: ./docker/nginx
    volumes:
      - /data/api.tienngay:/var/www/api.tienngay
      - /data/cpanel.tienngay:/var/www/cpanel.tienngay
      - /data/api.invest:/var/www/api.invest
      - /data/frontend.invest:/var/www/frontend.invest
      - /data/core.tienngay:/var/www/core.tienngay
      # Logs
      - ./docker/nginx/log:/var/log/nginx
    ports:
      - "81:81"
      - "82:82"
      - "83:83"
      - "84:84"
      - "85:85"
    networks:
      - all

  # PHP
  php:
    build: ./docker/php
    volumes:
      - /data/api.tienngay:/var/www/api.tienngay
      - /data/cpanel.tienngay:/var/www/cpanel.tienngay
      - /data/api.invest:/var/www/api.invest
      - /data/frontend.invest:/var/www/frontend.invest
      - /data/core.tienngay:/var/www/core.tienngay
      # Logs
      - ./docker/php/log:/var/log/php
    networks:
      - all

  # Mongodb
  mongodb:
    build: ./docker/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tungbt
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./docker/mongodb/mongoconfig:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - all

  # Mysql
  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_USER=invest
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - all

  # Kong
  kong:
    image: kong:latest
    volumes:
      - ./docker/kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./docker/kong/logs:/usr/local/kong/logs
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - all

  # Selenium
  # selenium:
  #   image: selenium/standalone-chrome
  #   ports:
  #     - "4444:4444"
  #     - "7900:7900"
  #   volumes:
  #     - ./docker/selenium/shm:/dev/shm
  #   networks:
  #     - all

  # ELK ES
  # elasticsearch:
  #   build: ./docker/elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   volumes:
  #     - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
  #     - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - all

  # ELK Kibana
  # kibana:
  #   build: ./docker/kibana
  #   volumes:
  #     - ./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - all
  #   depends_on:
  #     - elasticsearch

  # ELK Logstash
  # logstash:
  #   build: ./docker/logstash
  #   volumes:
  #     - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
  #     # Log
  #     - ./docker/php/log:/var/log/php
  #     - ./docker/nginx/log:/var/log/nginx
  #   networks:
  #     - all
  #   depends_on:
  #     - elasticsearch

networks: 
  all:
    driver: bridge