version: "3"
services:
  # Web
  nginx:
    build: ./docker/nginx
    volumes:
    - F:/Data/api.tienngay:/var/www/sandbox_api
    - F:/Data/cpanel.tienngay:/var/www/sandbox_cpanel
    - F:/Data/sandbox_invest:/var/www/sandbox_invest
    - F:/Data/frontend_invest:/var/www/frontend_invest
    # Logs
    - F:/Data/docker-lab/docker/nginx/log:/var/log/nginx
    ports:
      - "81:81"
      - "82:82"
      - "83:83"
      - "84:84"
    networks:
      - all

  # PHP
  php:
    build: ./docker/php
    volumes:
      - F:/Data/api.tienngay:/var/www/sandbox_api
      - F:/Data/cpanel.tienngay:/var/www/sandbox_cpanel
      - F:/Data/sandbox_invest:/var/www/sandbox_invest
      - F:/Data/frontend_invest:/var/www/frontend_invest
      # Logs
      - F:/Data/docker-lab/docker/php/log:/var/log/php
    networks:
      - all

  # Mongodb
  mongodb:
    build: ./docker/mongodb
    # volumes:
    #   - F:/Data/docker-lab/docker/mongodb/db:/data/db
    #   - F:/Data/docker-lab/docker/mongodb/mongo-entrypoint:/docker-entrypoint-initdb.d
    #   - F:/Data/docker-lab/docker/mongodb/mongoconfig:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - all

  # Mysql
  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_USER=invest
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - F:/Data/docker-lab/docker/selenium/shm:/dev/shm
    networks:
      - all

  # ELK ES
  elasticsearch:
    build: ./docker/elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - F:/Data/docker-lab/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - F:/Data/docker-lab/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - all

  # ELK Kibana
  kibana:
    build: ./docker/kibana
    volumes:
      - F:/Data/docker-lab/docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - all
    depends_on:
      - elasticsearch

  # ELK Logstash
  logstash:
    build: ./docker/logstash
    volumes:
      - F:/Data/docker-lab/docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - F:/Data/docker-lab/docker/logstash/pipeline:/usr/share/logstash/pipeline
      # Log
      - F:/Data/docker-lab/docker/php/log:/var/log/php
      - F:/Data/docker-lab/docker/nginx/log:/var/log/nginx
    networks:
      - all
    depends_on:
      - elasticsearch

networks: 
  all:
    driver: bridge