apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: all
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network/all: "true"
  podSelector:
    matchLabels:
      network/all: "true"
