apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    chart: tienngay
data:
  default.conf: |-
    server {
      listen 0.0.0.0:81;
      index index.php index.html;
      root /var/www;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      location / {
          try_files $uri /index.php?$args;
      }

      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass phpfpm-service:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configmap
  labels:
    chart: tienngay
data:
  .env: |-
    S3_BUCKET=devbucket
    MYSQL_HOST=mysql-cluster-service
    MYSQL_PORT=3306
    MYSQL_DB=test
    MYSQL_USER=tungbt
    MYSQL_PASS=12345678
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    chart: tienngay
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_USER: "tungbt"
  MYSQL_PASSWORD: "12345678"
  MYSQL_DATABASE: "test"
  MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password" 