apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: tienngay
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: www.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 81