apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongodb.matchLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "mongodb.labels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "12345678"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: tungbt
          image: mongodb
          name: mongodb
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          resources: {}
          volumeMounts:
            {{- range $subPath := .Values.mongodb.pvc }}
            - mountPath: {{ $subPath }}
              name: mongodb-pvc
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: mongodb-pvc
          persistentVolumeClaim:
            claimName: mongodb-pvc
