apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
