apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  name: mysql
spec:
  ports:
    - name: "{{ .Values.mysql.port }}"
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  selector:
    {{- include "mysql.labels" . | nindent 4 }}