apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginx.matchLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "nginx.labels" . | nindent 8 }}
    spec:
      containers:
        - image: nginx:1.19
          name: nginx
          ports:
            {{- range $port := .Values.nginx.ports }}
            - containerPort: {{ $port }}
            {{- end }}
          resources: {}
          volumeMounts:
            - mountPath: /var/www
              name: nginx-pvc
      restartPolicy: Always
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: nginx-pvc