apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /data/api.tienngay
  nodeAffinity:
    required:
      nodeSelectorTerms:
        -