apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "php.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "php.labels" . | nindent 8 }}
    spec:
      containers:
        - name: php
          image: php:7.3-fpm
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
          {{- range $subPath := .Values.php.pvc }}
            - mountPath: /var/www/{{ $subPath }}
              name: php-pvc
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: php-pvc
          persistentVolumeClaim:
            claimName: php-pvc