apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi