apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    chart: tienngay
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: phpfpm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    chart: tienngay
spec:
  type: LoadBalancer
  ports:
    - port: 81
      targetPort: 81
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip
  labels:
    chart: tienngay
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalance-ip
  labels:
    chart: tienngay
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql