version: "3.8"
services:

  traefik:
    image: traefik:v2.2
    ports:
      - 9093:80
      - 9090:8080
    networks:
      - proxy-net
    command:
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --api
      - --api.dashboard=true
      - --api.insecure=true
      - --accesslog
      - --log.level=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role==manager

  whoami:
    image: containous/whoami
    networks:
      - proxy-net
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy-net
        - traefik.http.services.whoami.loadbalancer.server.port=80
        - traefik.http.routers.whoami.service=whoami
        - traefik.http.routers.whoami.entrypoints=web
        - traefik.http.routers.whoami.rule=Host(`whoami.local`)
      placement:
        max_replicas_per_node: 1

  simpletwo:
    image: 192.168.0.72:5000/tungbt/simpletwo:1.0
    networks:
      - proxy-net
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy-net
        - traefik.http.services.simpletwo.loadbalancer.server.port=8080
        - traefik.http.routers.simpletwo.service=simpletwo
        - traefik.http.routers.simpletwo.entrypoints=web
        - traefik.http.routers.simpletwo.rule=Host(`simpletwo.local`)

  # # REDIS - master
  # redis-master:
  #   image: 'bitnami/redis:6.2.6'
  #   ports:
  #     - '9097:6379'
  #   networks:
  #     - proxy-net
  #   environment:
  #     - REDIS_REPLICATION_MODE=master
  #     - REDIS_PASSWORD=master_password
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role==manager

  # # REDIS - replica
  # redis-replica:
  #   image: 'bitnami/redis:6.2.6'
  #   ports:
  #     - '9098:6379'
  #   networks:
  #     - proxy-net
  #   depends_on:
  #     - redis-master
  #   environment:
  #     - REDIS_REPLICATION_MODE=slave
  #     - REDIS_MASTER_HOST=redis-master
  #     - REDIS_MASTER_PORT_NUMBER=6379
  #     - REDIS_MASTER_PASSWORD=master_password
  #     - REDIS_PASSWORD=replica_password

  # # REDIS - replica
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   networks:
  #     - proxy-net
  #   environment:
  #     - REDIS_HOSTS=redis-master:redis-master:6379:0:master_password
  #   ports:
  #     - "9099:8081"

  # # POSTGRE - master
  # postgresql-master:
  #   image: 'bitnami/postgresql:14.2.0'
  #   networks:
  #     - proxy-net
  #   ports:
  #     - '9080:5432'
  #   environment:
  #     - POSTGRESQL_REPLICATION_MODE=master
  #     - POSTGRESQL_REPLICATION_USER=repl_user
  #     - POSTGRESQL_REPLICATION_PASSWORD=repl_password
  #     - POSTGRESQL_USERNAME=root
  #     - POSTGRESQL_PASSWORD=12345678
  #     - POSTGRESQL_DATABASE=postgres
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role==manager

  # # POSTGRE - slave
  # postgresql-slave:
  #   image: 'bitnami/postgresql:14.2.0'
  #   networks:
  #     - proxy-net
  #   ports:
  #     - '9081:5432'
  #   environment:
  #     - POSTGRESQL_REPLICATION_MODE=slave
  #     - POSTGRESQL_REPLICATION_USER=repl_user
  #     - POSTGRESQL_REPLICATION_PASSWORD=repl_password
  #     - POSTGRESQL_MASTER_HOST=postgresql-master
  #     - POSTGRESQL_PASSWORD=12345678
  #     - POSTGRESQL_MASTER_PORT_NUMBER=5432

  # # POSTGRE - pgadmin4
  # pgadmin4:
  #   image: 'dpage/pgadmin4'
  #   networks:
  #     - proxy-net
  #   ports:
  #     - '9082:80'
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=12345678
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role==manager

networks:
  proxy-net:
    external: true
